/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrpcIndexRouteImport } from './routes/orpc/index'
import { Route as ReactHooksUseMemoIndexRouteImport } from './routes/react-hooks/use-memo/index'
import { Route as ReactHooksUseEffectIndexRouteImport } from './routes/react-hooks/use-effect/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrpcIndexRoute = OrpcIndexRouteImport.update({
  id: '/orpc/',
  path: '/orpc/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactHooksUseMemoIndexRoute = ReactHooksUseMemoIndexRouteImport.update({
  id: '/react-hooks/use-memo/',
  path: '/react-hooks/use-memo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactHooksUseEffectIndexRoute =
  ReactHooksUseEffectIndexRouteImport.update({
    id: '/react-hooks/use-effect/',
    path: '/react-hooks/use-effect/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orpc/': typeof OrpcIndexRoute
  '/react-hooks/use-effect/': typeof ReactHooksUseEffectIndexRoute
  '/react-hooks/use-memo/': typeof ReactHooksUseMemoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orpc': typeof OrpcIndexRoute
  '/react-hooks/use-effect': typeof ReactHooksUseEffectIndexRoute
  '/react-hooks/use-memo': typeof ReactHooksUseMemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/orpc/': typeof OrpcIndexRoute
  '/react-hooks/use-effect/': typeof ReactHooksUseEffectIndexRoute
  '/react-hooks/use-memo/': typeof ReactHooksUseMemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/orpc/'
    | '/react-hooks/use-effect/'
    | '/react-hooks/use-memo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/orpc' | '/react-hooks/use-effect' | '/react-hooks/use-memo'
  id:
    | '__root__'
    | '/'
    | '/orpc/'
    | '/react-hooks/use-effect/'
    | '/react-hooks/use-memo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrpcIndexRoute: typeof OrpcIndexRoute
  ReactHooksUseEffectIndexRoute: typeof ReactHooksUseEffectIndexRoute
  ReactHooksUseMemoIndexRoute: typeof ReactHooksUseMemoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orpc/': {
      id: '/orpc/'
      path: '/orpc'
      fullPath: '/orpc/'
      preLoaderRoute: typeof OrpcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-hooks/use-memo/': {
      id: '/react-hooks/use-memo/'
      path: '/react-hooks/use-memo'
      fullPath: '/react-hooks/use-memo/'
      preLoaderRoute: typeof ReactHooksUseMemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/react-hooks/use-effect/': {
      id: '/react-hooks/use-effect/'
      path: '/react-hooks/use-effect'
      fullPath: '/react-hooks/use-effect/'
      preLoaderRoute: typeof ReactHooksUseEffectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrpcIndexRoute: OrpcIndexRoute,
  ReactHooksUseEffectIndexRoute: ReactHooksUseEffectIndexRoute,
  ReactHooksUseMemoIndexRoute: ReactHooksUseMemoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
